import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

// 1. Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.skipWaiting();
clientsClaim();

// 2. Firebase Messaging Support
const firebaseConfig = {
  apiKey: "AIzaSyB2Z0mlvoz1vNy4jrBeccYB8q2bo_7DYI4",
  authDomain: "personal-smart-todo.firebaseapp.com",
  projectId: "personal-smart-todo",
  storageBucket: "personal-smart-todo.firebasestorage.app",
  messagingSenderId: "174319573850",
  appId: "1:174319573850:web:ed9506cfb8b7e9cb3e7163"
};

const app = initializeApp(firebaseConfig);
const messaging = getMessaging(app);

onBackgroundMessage(messaging, (payload) => {
  const notificationTitle = payload.notification.title || 'MyTODO Reminder';
  const notificationOptions = {
    body: payload.notification.body,
    icon: '/MyTODO/pwa-512x512.png',
    badge: '/MyTODO/favicon.svg',
    data: payload.data
  };
  self.registration.showNotification(notificationTitle, notificationOptions);
});

// 3. Custom Background Timers for Focus/Tasks
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SCHEDULE_NOTIFICATION') {
    const { title, body, delayMs, tag, timestamp } = event.data;
    
    const scheduledTime = timestamp || (Date.now() + delayMs);
    
    if ('showTrigger' in Notification.prototype && typeof self.TimestampTrigger !== 'undefined') {
      self.registration.showNotification(title, {
        body,
        icon: '/MyTODO/pwa-512x512.png',
        badge: '/MyTODO/favicon.svg',
        vibrate: [200, 100, 200],
        tag: tag || 'scheduled-notif',
        showTrigger: new self.TimestampTrigger(scheduledTime)
      });
    } else {
      const wait = Math.max(0, scheduledTime - Date.now());
      setTimeout(() => {
        self.registration.showNotification(title, {
          body,
          icon: '/MyTODO/pwa-512x512.png',
          badge: '/MyTODO/favicon.svg',
          vibrate: [200, 100, 200],
          tag: tag || 'scheduled-notif',
          renotify: true
        });
      }, wait);
    }
  }
});

// 4. Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        return clientList[0].focus();
      }
      return clients.openWindow('/MyTODO/');
    })
  );
});
