import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

// 1. Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.skipWaiting();
clientsClaim();

// 2. Firebase Messaging Support
importScripts('https://www.gstatic.com/firebasejs/11.0.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/11.0.0/firebase-messaging-compat.js');

const firebaseConfig = {
  apiKey: "AIzaSyB2Z0mlvoz1vNy4jrBeccYB8q2bo_7DYI4",
  authDomain: "personal-smart-todo.firebaseapp.com",
  projectId: "personal-smart-todo",
  storageBucket: "personal-smart-todo.firebasestorage.app",
  messagingSenderId: "174319573850",
  appId: "1:174319573850:web:ed9506cfb8b7e9cb3e7163"
};

if (firebase.apps.length === 0) {
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    const notificationTitle = payload.notification.title || 'MyTODO Reminder';
    const notificationOptions = {
      body: payload.notification.body,
      icon: '/MyTODO/pwa-512x512.png',
      badge: '/MyTODO/favicon.svg',
      data: payload.data
    };
    self.registration.showNotification(notificationTitle, notificationOptions);
  });
}

// 3. Custom Background Timers for Focus/Tasks
// This allows the app to "schedule" a notification even if it's closed.
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SCHEDULE_NOTIFICATION') {
    const { title, body, delayMs, tag, timestamp } = event.data;
    
    // Calculate target time
    const scheduledTime = timestamp || (Date.now() + delayMs);
    
    // Feature Detection: Notification Triggers (Persistent local scheduling)
    if ('showTrigger' in Notification.prototype) {
      self.registration.showNotification(title, {
        body,
        icon: '/MyTODO/pwa-512x512.png',
        badge: '/MyTODO/favicon.svg',
        vibrate: [200, 100, 200],
        tag: tag || 'scheduled-notif',
        showTrigger: new TimestampTrigger(scheduledTime)
      });
    } else {
      // Fallback: Use setTimeout (less reliable if SW is killed)
      const wait = Math.max(0, scheduledTime - Date.now());
      setTimeout(() => {
        self.registration.showNotification(title, {
          body,
          icon: '/MyTODO/pwa-512x512.png',
          badge: '/MyTODO/favicon.svg',
          vibrate: [200, 100, 200],
          tag: tag || 'scheduled-notif',
          renotify: true
        });
      }, wait);
    }
  }
});

// 4. Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // Open the app when notification is clicked
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        return clientList[0].focus();
      }
      return clients.openWindow('/MyTODO/');
    })
  );
});
